"""add foreign key to Review

Revision ID: 7cf72a17a31f
Revises: 34d1341d5639
Create Date: 2025-06-20 12:29:40.495872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf72a17a31f'
down_revision = '34d1341d5639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_reviews_employee_id_employees"),
        "reviews",
        "employees",
        ["employee_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_reviews_employee_id_employees"), "reviews", type_="foreignkey"
    )
    # ### end Alembic commands ###
